[package]
name = "AptID"
version = "0.0.1"

[addresses]
apt_id = "0x045317f67a03b2c226eb2a468d91cea2ea92eaa7987a567288a36560a3b43414"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }
