[package]
name = "AptID"
version = "0.0.1"

[addresses]
apt_id = "0xc7050e4a5fce7292e0e7def652d70e79447fce2d6edb00a1e1fdb3d711978beb"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }
