[package]
name = "DotAptTLD"
version = "0.0.1"

[addresses]
dot_apt_registrar = "0xf71cb5dc58c4290a2cc009ba5c87f389ca624e1d6b9b9135c2b4c43c1bb69cb6"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }
AptID = { local = "../apt_id" }
