[package]
name = "DotAptTLD"
version = "0.0.1"

[addresses]
dot_apt_registrar = "0x8add34212cbe560856ac610865f9bc2e4ac49b65739d58e7f2c87125d73bad02"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }
AptID = { local = "../apt_id" }
